name: amazon_gpu
channels:
  - defaults
  - nvidia
dependencies:
  - python=3.9
  - pip
  - nvidia/label/cuda-11.8.0::cuda
  - h5py=3.12.1
  - joblib=1.4.2
  - loguru=0.7.2
  - numpy=2.0.2
  - orjson=3.10.14
  - pandas=2.2.3
  - py7zr=0.20.5
  - python-dotenv=0.21.0
  - scipy=1.13.1
  - scikit-learn=1.6.1
  - tqdm=4.67.1
  - pip:
      - ltntorch==1.0.2
      - orjsonl==1.0.0
      - torch==2.6.0
      - wandb==0.19.6