name: amazon_cpu
channels:
  - defaults
dependencies:
  - python=3.9
  - pytorch::pytorch=2.5.1
  - pytorch::cpuonly=2.0
  - tqdm=4.66.5
  - orjson=3.10.7
  - loguru=0.7.2
  - numpy=1.26.4
  - scipy=1.13.1
  - scikit-learn=1.5.1
  - pandas=2.2.3
  - py7zr=0.20.5
  - joblib=1.4.2
  - pip
  - pip:
      - ltntorch==1.0.2
      - wandb==0.19.0