name: data_processing
channels:
  - defaults
dependencies:
  - joblib=1.4.2
  - loguru=0.7.2
  - orjson=3.10.7
  - python=3.13.1
  - tqdm=4.63.0
  - pandas=2.2.3
  - pip=24.2
  - pip:
      - neo4j-rust-ext==5.27.0.0
      - tqdm-loggable==0.2
      - python-dotenv==1.0.1
      - orjsonl==1.0.0