# manually add pytorch and cuda installation as per your hardware requirements
name: amazon_gpu
channels:
  - defaults
dependencies:
  - python=3.9
  - tqdm
  - orjson
  - loguru
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - py7zr
  - python-dotenv
  - pip
  - pip:
      - wandb