name: amazon_gpu
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - tqdm
  - orjson
  - loguru
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - py7zr
  - python-dotenv
  - pytorch
  - pytorch-cuda=11.8
  - pip
  - pip:
      - wandb