name: SemNeSyKTRecSys
dependencies:
  - python=3.9
  - conda-forge::graph-tool
  - conda-forge::jupyterlab
  - anaconda::sqlite=3.40.0
  - pip
  - pip:
    - kgtk==1.5.4
    - joblib==1.4.2
    - pandas==2.2.2
    - beautifulsoup4==4.12.2
    - selenium==4.20.0
    - SPARQLWrapper==2.0.0
    - tqdm==4.66.4
    - wayback==0.4.5
    - aiohttp==3.9.5
    - backoff==2.2.1
    - requests==2.31.0
    - aiolimiter==1.1.0
    - python-dotenv==1.0.1