name: data_processing
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.5
  - aiolimiter=1.2.1
  - aiosignal=1.2.0
  - attrs=24.2.0
  - backoff=2.2.1
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bs4=4.12.3
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - certifi=2024.8.30
  - click=8.1.7
  - colorama=0.4.6
  - cyrus-sasl=2.1.28
  - exceptiongroup=1.2.0
  - expat=2.6.4
  - fake-useragent=1.4.0
  - frozenlist=1.5.0
  - h11=0.14.0
  - idna=3.7
  - intel-openmp=2023.1.0
  - isodate=0.7.2
  - joblib=1.4.2
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libmpdec=4.0.0
  - libpq=17.2
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - loguru=0.7.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - multidict=6.1.0
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=2.1.3
  - numpy-base=2.1.3
  - openldap=2.6.4
  - openssl=3.0.15
  - orjson=3.10.7
  - outcome=1.1.0
  - pandas=2.2.3
  - pip=24.2
  - propcache=0.2.0
  - psycopg=3.2.3
  - psycopg-c=3.2.3
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.13.1
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-tzdata=2023.3
  - python_abi=3.13
  - pytz=2024.1
  - rdflib=7.1.1
  - readline=8.2
  - regex=2024.9.11
  - selenium=4.27.1
  - selenium-manager=4.27.0
  - setuptools=72.1.0
  - six=1.16.0
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sparqlwrapper=2.0.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tqdm=4.63.0
  - trio=0.26.2
  - trio-websocket=0.11.1
  - typing_extensions=4.11.0
  - tzdata=2024b
  - urllib3=2.2.3
  - websocket-client=1.8.0
  - wheel=0.44.0
  - wsproto=1.2.0
  - xz=5.4.6
  - yarl=1.18.0
  - zlib=1.2.13
  - pip:
      - charset-normalizer==3.4.0
      - jaro-winkler==2.0.3
      - neo4j==5.27.0
      - neo4j-rust-ext==5.27.0.0
      - psycopg-pool==3.2.4
      - requests==2.32.3
      - typing-extensions==4.12.2
      - wayback==0.4.5